<template>
  <v-row justify="center" align="baseline">
    <v-col>
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/autoparts"
      >
        ข้อมูลอะไหล่ยนต์
      </v-btn>
    </v-col>
    <v-col>
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/takeaparts"
      >
        เบิกอะไหล่
      </v-btn>
    </v-col>
    <v-col>
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/reportday"
      >
        สรุปรายงาน
      </v-btn>
    </v-col>
    <v-col>
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/dataemployee"
      >
        ข้อมูลพนักงาน
      </v-btn>
    </v-col>
    <v-col cols="36" md="36" sm="12">
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/buyautoparts"
      >
        สั่งซื้ออะไหล่
      </v-btn>
    </v-col>
    <v-col cols="36" md="36" sm="12">
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/notifications"
      >
        การแจ้งเตือน
      </v-btn>
    </v-col>
  </v-row>
</template>

<script>
export default {
  name: "IndexPage",
};
</script>