<template>
  <v-row justify="center" align="baseline">
    <v-col>
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/partsreport"
      >
        ดูประวัติการเพิ่มอะไหล่
      </v-btn>
    </v-col>
    <v-col cols="36" md="36" sm="12">
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/buyparts"
      >
        ดูประวัติการกำหนดราคา
      </v-btn>
    </v-col>
    <v-col cols="36" md="36" sm="12">
      <v-btn
        color="primary"
        depressed
        elevation="36"
        large
        x-large
        nuxt
        to="/reportday"
      >
        ดูประวัติการเบิก
      </v-btn>
    </v-col>
  </v-row>
</template>